language: objective-c
osx_image: xcode8

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods

install:
  - pod install

script:
  - set -o pipefail &&  xcodebuild -workspace NKJModalSelector-Demo.xcworkspace -scheme NKJModalSelector-Demo -destination 'platform=iOS Simulator,name=iPhone 6' -configuration Debug clean build TEST_AFTER_BUILD=YES | xcpretty
  - pod lib lint --quick
